// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwPHwTMaomx4vNh-1S88808WmmkDw-0VM',
    appId: '1:409136332607:web:c756f928fc225146485d8a',
    messagingSenderId: '409136332607',
    projectId: 'smartlock-54fa4',
    authDomain: 'smartlock-54fa4.firebaseapp.com',
    databaseURL: 'https://smartlock-54fa4-default-rtdb.firebaseio.com',
    storageBucket: 'smartlock-54fa4.firebasestorage.app',
    measurementId: 'G-033945KYW8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCevhdvN3aGSfWmj1q5dQJEzsNSp-1F8CE',
    appId: '1:409136332607:android:b2b086de1a5f1b6a485d8a',
    messagingSenderId: '409136332607',
    projectId: 'smartlock-54fa4',
    databaseURL: 'https://smartlock-54fa4-default-rtdb.firebaseio.com',
    storageBucket: 'smartlock-54fa4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkYOvTt6-wT0fpTHZgVbX4ueDbrUODzBo',
    appId: '1:409136332607:ios:0a87855f8f698698485d8a',
    messagingSenderId: '409136332607',
    projectId: 'smartlock-54fa4',
    databaseURL: 'https://smartlock-54fa4-default-rtdb.firebaseio.com',
    storageBucket: 'smartlock-54fa4.firebasestorage.app',
    iosBundleId: 'com.example.smartlocks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkYOvTt6-wT0fpTHZgVbX4ueDbrUODzBo',
    appId: '1:409136332607:ios:0a87855f8f698698485d8a',
    messagingSenderId: '409136332607',
    projectId: 'smartlock-54fa4',
    databaseURL: 'https://smartlock-54fa4-default-rtdb.firebaseio.com',
    storageBucket: 'smartlock-54fa4.firebasestorage.app',
    iosBundleId: 'com.example.smartlocks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwPHwTMaomx4vNh-1S88808WmmkDw-0VM',
    appId: '1:409136332607:web:35c10ff46c14e723485d8a',
    messagingSenderId: '409136332607',
    projectId: 'smartlock-54fa4',
    authDomain: 'smartlock-54fa4.firebaseapp.com',
    databaseURL: 'https://smartlock-54fa4-default-rtdb.firebaseio.com',
    storageBucket: 'smartlock-54fa4.firebasestorage.app',
    measurementId: 'G-07V0BQ48NN',
  );
}
